# Generated by Django 4.2.3 on 2023-08-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chef_food_description_alter_food_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chef',
            options={'verbose_name': 'Chef', 'verbose_name_plural': 'Chefs'},
        ),
    ]
