# Generated by Django 4.2.3 on 2023-08-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_chef_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=13)),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('people', models.IntegerField(default=1)),
                ('message', models.TextField()),
            ],
        ),
    ]
